"""empty message

Revision ID: 2b78706cf6fa
Revises: 
Create Date: 2024-03-07 17:47:22.882450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b78706cf6fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcq_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=120), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answerCode', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('true_false_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('answerCode', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('true_false_answer')
    op.drop_table('mcq_answer')
    # ### end Alembic commands ###
